modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/team-abnormals/pet-cemetery/issues"
license = "https://github.com/team-abnormals/pet-cemetery/blob/main/LICENSE.txt"

[[mods]]
    modId = "pet_cemetery"
    version = "${mod_version}"
    logoFile = "logo.png"
    itemIcon = "pet_cemetery:pet_collar"
    configBackground = "minecraft:textures/block/weathered_copper.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, hatsondogs"
    displayURL = "https://www.teamabnormals.com/mods/pet-cemetery"
    displayName = "Pet Cemetery"
    description = '''
    Bring back your fallen friends!
    '''

[[mixins]]
    config = "pet_cemetery.mixins.json"

[[dependencies.pet_cemetery]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${mc_version}]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.pet_cemetery]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge},)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.pet_cemetery]]
    modId = "blueprint"
    type = "required"
    versionRange = "[${blueprint},)"
    ordering = "AFTER"
    side = "BOTH"